"""posts table

Revision ID: 182aacb3fd5a
Revises: 8e86c4e62f13
Create Date: 2019-04-25 17:55:31.243104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182aacb3fd5a'
down_revision = '8e86c4e62f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('modification_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_creation_date'), 'post', ['creation_date'], unique=False)
    op.create_index(op.f('ix_post_modification_date'), 'post', ['modification_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_modification_date'), table_name='post')
    op.drop_index(op.f('ix_post_creation_date'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
